const chalk = require('chalk');
const appRoot = require('app-root-path');
const pack = require(appRoot + '/node_modules/hexo-theme-aurora/package.json');
require('./lib/filters')(hexo);
require('./lib/generators')(hexo);
require('./lib/injector')(hexo);

hexo.on('generateAfter', function () {
  console.log(
    chalk.green('INFO ') +
      chalk.yellow('API data generated by') +
      chalk.cyan.bold(' Aurora v' + pack.version)
  );
});

hexo.on('exit', function () {
  console.log(
    chalk.green('INFO ') +
      chalk.magenta('Thanks for using') +
      chalk.cyan.bold(' Aurora Plugin v' + pack.version)
  );
  console.log(
    chalk.green('INFO ') +
      chalk.magenta('Check out the repo at:') +
      chalk.cyan.underline(' https://github.com/auroral-ui/hexo-theme-aurora')
  );
});
